package:  focuspoint
version:  '1.3.8'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/focuspoint


page:
    title: 'translate:title'
    perm: focuspoint[]
    icon: rex-icon fa-dot-circle-o
    subpages:
      info: { title: 'translate:info'}
      help: { title: 'translate:help'}
      changelog: { title: 'translate:changelog'}
      license: { title: 'translate:license'}

requires:
    packages:
        metainfo: '^2.0'
        media_manager: '^2.0'
    redaxo: '^5.1.0'
    php:
        version: '>=5.6'
