package:  focuspoint
version:  '2.0.0-dev'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/focuspoint
#load: late

help:
    mode: docs
    fallback: de_de
    navigation: main_navi.md
    content: main_intro.md
    repository: https://github.com/FriendsOfREDAXO/focuspoint/%%

pages:
    # media_manager/overview wird zu einem Untermenü, wenn fp sich einklinkt
    # daher den Originaltext zum ersten Menüpunkt machen.
    media_manager/overview/overview:
        subPath: ../media_manager/pages/overview.php
        title: 'Media Manager'
        icon: rex-icon fa-info-circle
    media_manager/overview/focuspoint:
        subPath: help.php
        title: 'translate:focuspoint_doc'
        icon: rex-icon fa-info-circle
        help: { mode: docs, navigation: mm_navi.md, content: mm_effect_fit.md }

requires:
    php:
        version: '>=5.6'
    redaxo: '^5.6.0'
    packages:
        metainfo: '^2.3.1'
        media_manager: '^2.5.4'
