package:  focuspoint
version:  '1.4.1'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/focuspoint


page:
requires:
    packages:
        metainfo: '^2.0'
        media_manager: '^2.0'
    redaxo: '^5.1.0'
    php:
        version: '>=5.6'
