package:  focuspoint
version:  '4.0.3'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/focuspoint

pages:
    # Seite "media_manager/overview" wird zu einem Untermen端, wenn fp sich einklinkt
    # daher die Originalseite zum ersten Men端punkt machen.
    media_manager/overview/overview:
        subPath: ../media_manager/README.md
        title: translate:media_manager_subpage_desc
    media_manager/overview/focuspoint:
        subPath: help.php
        title: translate:focuspoint_doc
        icon: rex-icon rex-icon-info

requires:
    packages:
        media_manager: '^2.12.0'
        mediapool: '^2.11.0'
    redaxo: '^5.13.0'
    php:
        version: '>=7.3'

help:
    # Default-View, f端r page=packages (Aufruf aus der Addon-Verwaltung)
    default:
        initial: docs/overview.md
        0:
            title: translate:focuspoint_docs_overview
            icon: fa fa-book
            path: docs/overview.md
        1:
            title: translate:focuspoint_docs_edit
            icon: fa fa-book
            path: docs/edit.md
        2:
            title: translate:focuspoint_docs_mm
            icon: fa fa-book
            path: docs/media_manager.md
        3:
            title: translate:focuspoint_docs_install
            icon: fa fa-book
            path: docs/install.md
        4:
            title: translate:focuspoint_docs_api
            icon: fa fa-book
            path: docs/developer.md
    # menu-structure f端r media_manager (siehe dessen Sektion "pages:")
    media_manager/overview/focuspoint:
        0:
            title: translate:focuspoint_effect_fit
            icon: fa fa-book
            path: docs/media_manager.md
        1:
            title: translate:focuspoint_doc
            icon: fa fa-book
            href: ?page=packages&subpage=help&package=focuspoint
