package:  focuspoint
version:  '0.5'
author:   Oliver Kreischer, Jan Kristinus, Thomas, Blum, Daniel Weitenauer
supportpage: www.redaxo.org/de/forum

page:
    title: 'translate:title'
    perm: focuspoint[]
    icon: rex-icon fa-dot-circle-o
    subpages:
      info: { title: 'translate:info'}
      help: { title: 'translate:help'}
      changelog: { title: 'translate:changelog'}
      license: { title: 'translate:license'}
