package:  focuspoint
version:  '2.1.3'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/focuspoint

help:
    mode: docs
    fallback: de_de
    navigation: main_navi.md
    content: main_intro.md
    repository: https://github.com/FriendsOfREDAXO/focuspoint/%%

pages:
    # Seite "media_manager/overview" wird zu einem Untermenü, wenn fp sich einklinkt
    # daher die Originalseite zum ersten Menüpunkt machen.
    media_manager/overview/overview:
        subPath: ../media_manager/README.md
        title: 'translate:media_manager_subpage_desc'
    media_manager/overview/focuspoint:
        subPath: help.php
        title: 'translate:focuspoint_doc'
        icon: rex-icon fa-info-circle
        help: { mode: docs, navigation: mm_navi.md, content: mm_effect_fit.md }

requires:
    packages:
        media_manager: '^2.7.0'
    redaxo: '^5.8.0'
