<link rel="stylesheet" href="/assets/addons/focuspoint/focuspoint.css" />

<!-- jQuery Einbindung Anfang
     Nur notwendig wenn jQuery nicht anders eingebunden wird ->
<script type="text/javascript" src="http://code.jquery.com/jquery-2.1.0.min.js" /></script>
<!-- // Query Einbindung Ende -->

<script type="text/javascript" src="./assets/addons/focuspoint/jquery_focuspoint.js"></script>
<script type="text/javascript">
$( document ).ready(function() {
  $('.focuspoint').focusPoint();
});
</script>
